[nfs]
172.31.23.69 ansible_user="ec2-user"

[webservers]
172.31.18.244 ansible_user="ec2-user"
172.31.31.247 ansible_user="ec2-user"

[db]
172.31.90.179 ansible_user="ec2-user" 

[lb]
172.31.90.11 ansible_user="ubuntu"